---
title: "SA Voting Habits"
output: NA
---

```{r setup}
library(haven)
library(scales)
library(ftplottools)
library(plyr)
library(tidyverse)
library(conflicted)
conflict_prefer("summarise", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("mutate", "dplyr")
```

```{r}
youngest_age_at_1994 <- 5
oldest_age_at_1994 <- 65
```


```{r}
voter_behaviour <- 
  read_tsv("sasas_ddk12.tab") %>% 
  select(vote, year, age, race, force) %>%
  mutate(age_at_1994 = force + 18) %>% 
  filter(!is.na(vote),
         !is.na(race),
         race %in% c(1, 4),
         age_at_1994 > youngest_age_at_1994,
         age_at_1994 < oldest_age_at_1994
         ) %>% 
  mutate(race = case_when(
    race == 1 ~ "Blacks",
    race == 4 ~ "Whites",
    TRUE ~ as.character(race)
  )) %>% 
  mutate(age_at_1994 = round_any(age_at_1994, 1)) %>%
  group_by(age_at_1994, race) %>% 
  summarise(mean_vote = mean(vote),
            n_obs = n())

voter_behaviour
```


```{r}
voter_behaviour %>%
  ggplot(aes(x = age_at_1994, y = mean_vote, color = race)) +
  geom_point() +
  geom_smooth(se = F, span = 0.5) +
  scale_color_manual(values = ft_colors("claret", "oxford")) +
  geom_vline(xintercept = 18, color = ft_colors("black-70")) +
  ft_theme(legend_right = T) +
  scale_y_continuous(labels = label_percent(), 
                     # expand = expansion(mult = c(0,0.3)),
                     breaks = seq(0, 1, 0.25),
                     expand = c(0, 0),
                     limits = c(0, 1.3)
                     ) +
  scale_x_continuous(expand = c(0,0), 
                     limits = c(youngest_age_at_1994, 
                                oldest_age_at_1994)) +
  labs(color = NULL,
       y = NULL,
       subtitle = str_c("Proportion responding 'Yes' when asked: ",
                        "'Did you vote in the last election?'\n"),
       title = "Poles apart: voting habits in South Africa",
       caption = str_c("Source: ",
                        #"Human Sciences Research Council (HSRC), ",
                       "South African Social Attitudes Survey, ",
                       "2003–2011; Dan Sands De Kadt",
                       "\n**Year of South Africa's first democratic election"),
       x = "Age at 1994**") +
  annotate("text", 
           x = 10, 
           y = 1.2, 
           size = 3,
           hjust = 0.5,
           vjust = 0.5,
           label = "Younger than\n18 in 1994") +
  annotate("text", 
           x = 18, 
           y = 1.2, 
           size = 6,
           hjust = 1,
           vjust = 0.5,
           label = "\u2190") +
  annotate("text", 
           x = 26, 
           y = 1.2, 
           size = 3,
           hjust = 0.5,
           vjust = 0.5,
           label = "Older than\n18 in 1994") +
  annotate("text", 
           x = 18, 
           y = 1.2, 
           size = 6,
           hjust = 0,
           vjust = 0.5,
           label = "\u2192") +
  theme(axis.title.x = element_text(margin = margin(t = 8)),
        plot.caption = element_text(size = 8, margin = margin(t = 8))) 
```

